.\" Manpage for lcs
.\" Contect jrmarsha@mtu.edu about any issues
.\"
.TH "lcs" "1.0" "lcs man page"
.SH NAME
lcs \- Longest Common Subsequence mapper
.SH SYNOPSIS
.B lcs [FILE 1] [FILE 2]
.SH DESCRIPTION
lcs is a tool by which the contents of two file are analysed in order to
determine the mapping of indexes from the first file to the second such 
that the indexes relate to the other through pointing to the Longest
Common Subsequence in each file.
.SH BUGS
No known bugs at the tieme of writing.
.SH AUTHOR
Josh Marshall <jrmarsha at mtu dot edu>
.SH SEE ALSO
.BR regex(1)

